n1 = int(input('Digite um número: '))
a= n1*1
b = n1*2
c= n1 *3
d= n1 *4
e= n1 *5
f= n1 *6
g= n1 *7
h= n1 *8
i= n1 *9
j= n1 *10
print('{} x 1 = {}'.format(n1, a))
print('{} x 2 = {}'.format(n1,b))
print('{} x 3 = {}'.format(n1,c))
print('{} x 4 = {}'.format(n1,d))
print('{} x 5 = {}'.format(n1,e))
print('{} x 6 = {}'.format(n1,f))
print('{} x 7 = {}'.format(n1,g))
print('{} x 8 = {}'.format(n1,h))
print('{} x 9 = {}'.format(n1,i))
print('{} x 10 = {}'.format(n1,j))

